export { default as Hero } from "./Hero"
export { default as TimeWorking } from "./TimeWorking"
export { default as Tools } from "./Tools"
export { default as ProblemSolved } from "./ProblemsSolved"
export {default as ImproveWorkflow} from "./ImproveWorkflow"
export { default as Community } from "./Community"
